FROM yurikrupnik/client-apps_lerna AS builder

ARG port=6002
ENV PORT=$port

COPY ./packages ./packages
COPY docs ./docs
RUN npm run pi
RUN npx lerna run build --scope @krupnik/fe-docs

FROM node:12-alpine
WORKDIR /usr/src/app
COPY --from=builder /app/packages/docs/dist .
RUN npm install --only=production

EXPOSE 6002
CMD ["npm", "start"]
